#!/bin/bash

bash tests/runRefCompile.sh
javac BackendTest.java

failed=0
total=0

runBackendTest(){
    java BackendTest "$1"
    code=$?
    ((total=total+1))
    if [ $code -ne 0 ]; then
        (( failed = failed + 1 ))
        echo "Error: Output Mismatch for $1"
    else
    echo "Backend Test Passed: $1"
    fi
}


echo "=============== Running Backend Tests ==============="
echo "..."
runBackendTest tests/examples/valid/basic/skip/skip.wacc
runBackendTest tests/examples/valid/basic/skip/comment.wacc
runBackendTest tests/examples/valid/basic/skip/commentInLine.wacc

rm -fr BackendTest.class *.s *.out

((passed=total-failed))

echo "Passed $passed / $total"

if [ "$passed" -ne "$total" ]; then
    exit 1
fi