#!/bin/bash
a=$1
b=${a%.s}
FILENAME=$(basename $b)
arm-linux-gnueabi-gcc -o $FILENAME -mcpu=arm1176jzf-s -mtune=arm1176jzf-s $FILENAME.s
qemu-arm -L /usr/arm-linux-gnueabi/ $FILENAME
echo "Exit Code: " $?
rm $FILENAME
